[workspace]
resolver = "2"
members = [
    "simba",
    "simba-cmd",
    "visualizer",
    "native-gui",
    "cow-tree",
#    "web-gui",
]

[workspace.dependencies]
asim = { git="http://github.com/kaimast/asim.git" }
log = "0.4"
rand = "0.9"
getrandom = "0.3"
ron = "0.11"
console-subscriber = "0.4"
dashmap = "6"
#winit = "0.30"
winit = { git = "https://github.com/iced-rs/winit.git", rev="05b8ff17a06562f0a10bb46e6eaacbe2a95cb5ed" }

[workspace.dependencies.wgpu]
version="26"
features=["spirv"]

[workspace.dependencies.iced_aw]
git="https://github.com/iced-rs/iced_aw.git"
default-features=false

[workspace.dependencies.iced_winit]
#version = "0.14"
git="https://github.com/iced-rs/iced.git"

[workspace.dependencies.iced]
#version = "0.14"
git="https://github.com/iced-rs/iced.git"
features=["tokio", "wgpu"]
default-features=false

[workspace.dependencies.iced_renderer]
#version = "0.14"
git="https://github.com/iced-rs/iced.git"
default-features=false

[workspace.dependencies.iced_wgpu]
#version = "0.14"
git="https://github.com/iced-rs/iced.git"

[profile.release]
opt-level = 3
debug = true

[profile.dev.build-override]
opt-level = 3

[patch.crates-io]
iced = { git="https://github.com/iced-rs/iced.git"}
iced_core = { git="https://github.com/iced-rs/iced.git"}
iced_widget = { git="https://github.com/iced-rs/iced.git"}
winit = { git = "https://github.com/iced-rs/winit.git", rev="05b8ff17a06562f0a10bb46e6eaacbe2a95cb5ed" }
