use std::sync::Arc;
use std::sync::Mutex as StdMutex;

use winit::dpi::PhysicalPosition;

use iced::keyboard::{Event as KeyboardEvent, Key, key};
use iced::mouse::{
    Button as MouseButton, Event as MouseEvent, ScrollDelta as MouseScrollDelta,
};
use iced::{Event, Font, Pixels};
use iced_wgpu::graphics::Viewport;
use iced_winit::conversion;
use iced_winit::core::{mouse, renderer};
use iced_winit::runtime::user_interface::{self, UserInterface};

use simba::Simulation;

use crate::graphics::Geometry;
use crate::graphics::{InputDirection, Renderer};
use crate::scene::SceneManager;
use crate::ui::{CursorPosition, UiEvents, UiLogic, UiMessages};

pub struct UiRenderLoop {
    renderer: Arc<Renderer>,
    messages: Arc<UiMessages>,
    events: Arc<UiEvents>,
    controls: UiLogic,
    cursor_position: Arc<StdMutex<PhysicalPosition<f64>>>,
    ui_renderer: iced_wgpu::Renderer,
    clipboard: iced_winit::Clipboard,
    scene_manager: Arc<SceneManager>,
    cache: user_interface::Cache,
    cursor: mouse::Cursor,
}

impl UiRenderLoop {
    #[allow(clippy::too_many_arguments)]
    pub async fn new(
        renderer: Arc<Renderer>,
        messages: Arc<UiMessages>,
        events: Arc<UiEvents>,
        cursor_position: Arc<CursorPosition>,
        window: Arc<winit::window::Window>,
        simulation: Arc<Simulation>,
        scene_manager: Arc<SceneManager>,
    ) -> Self {
        let clipboard = iced_winit::Clipboard::connect(window);

        let device = renderer.get_device().clone();
        let queue = renderer.get_render_queue().clone();

        let engine = iced_wgpu::Engine::new(
            renderer.get_adapter(),
            device,
            queue,
            renderer.get_texture_format(),
            None, // No antialiasing
        );

        let ui_renderer =
            iced_wgpu::Renderer::new(engine, Font::with_name("Fira Sans"), Pixels(16.0));

        let controls = UiLogic::new(simulation, scene_manager.clone(), messages.clone());

        Self {
            messages,
            events,
            renderer,
            clipboard,
            ui_renderer,
            cursor_position,
            controls,
            scene_manager,
            cache: user_interface::Cache::new(),
            cursor: mouse::Cursor::Unavailable,
        }
    }

    pub async fn update_and_draw(
        &mut self,
        geometry: Geometry,
        window: &winit::window::Window,
        surface_view: &wgpu::TextureView,
    ) {
        let viewport = Viewport::with_physical_size(
            iced::Size::new(geometry.window_size.width, geometry.window_size.height),
            geometry.scale_factor as f32,
        );

        // Update cursor position
        let cursor_position = *self.cursor_position.lock().unwrap();
        self.cursor = mouse::Cursor::Available(conversion::cursor_position(
            iced_winit::winit::dpi::PhysicalPosition::new(
                cursor_position.x,
                cursor_position.y,
            ),
            geometry.scale_factor as f32,
        ));

        log::trace!("Processing UI events and messages");

        // Process all pending events first
        let events = self.events.lock().unwrap().drain(..).collect::<Vec<_>>();
        
        if !events.is_empty() {
            // Build the UI
            let mut interface = UserInterface::build(
                self.controls.view(),
                viewport.logical_size(),
                std::mem::take(&mut self.cache),
                &mut self.ui_renderer,
            );

            let mut messages = Vec::new();

            // Update the UI with events
            let (_state, event_statuses) = interface.update(
                &events,
                self.cursor,
                &mut self.ui_renderer,
                &mut self.clipboard,
                &mut messages,
            );

            self.cache = interface.into_cache();

            // Process any messages generated by the UI
            for message in messages {
                self.controls.update(message);
            }

            // Handle events that the UI didn't consume (Status::Ignored)
            // These are for scene interactions like clicking on nodes, camera control, etc.
            for (event, status) in events.iter().zip(event_statuses.iter()) {
                if status == &iced::event::Status::Ignored {
                    self.handle_event(event.clone());
                }
            }
        }

        // Process pending messages from the application
        for msg in self.messages.take() {
            self.controls.update(msg);
        }

        // Draw the UI
        log::trace!("Drawing UI");

        // Build the UI for drawing
        let mut interface = UserInterface::build(
            self.controls.view(),
            viewport.logical_size(),
            std::mem::take(&mut self.cache),
            &mut self.ui_renderer,
        );

        // Update with a RedrawRequested event to ensure proper rendering
        let (_state, _) = interface.update(
            &[Event::Window(iced::window::Event::RedrawRequested(
                iced::time::Instant::now(),
            ))],
            self.cursor,
            &mut self.ui_renderer,
            &mut self.clipboard,
            &mut Vec::new(),
        );

        // Update mouse cursor
        if let user_interface::State::Updated {
            mouse_interaction, ..
        } = _state
        {
            window.set_cursor(conversion::mouse_interaction(mouse_interaction));
        }

        // Draw the interface
        interface.draw(
            &mut self.ui_renderer,
            &iced::Theme::Light,
            &renderer::Style {
                text_color: iced::Color::BLACK,
            },
            self.cursor,
        );

        self.cache = interface.into_cache();

        // Present to the surface
        self.ui_renderer.present(
            None, // clear_color - we don't clear since we draw on top of the scene
            self.renderer.get_texture_format(),
            surface_view,
            &viewport,
        );

        log::trace!("UI rendering complete");
    }

    fn handle_event(&self, event: Event) {
        match event {
            Event::Mouse(mouse_event) => {
                match mouse_event {
                    MouseEvent::WheelScrolled { delta } => {
                        // TODO add mouse sensitivity settings
                        let mouse_scale_factor = 0.02;

                        log::trace!("Mouse wheel event: {delta:?}");

                        let change = match delta {
                            MouseScrollDelta::Lines { x: _, y } => 10.0 * y,
                            MouseScrollDelta::Pixels { x: _, y } => y,
                        };

                        if change != 0.0 {
                            let camera = self.scene_manager.get_active_camera();
                            camera.change_zoom_by(change * mouse_scale_factor);
                        }
                    }
                    MouseEvent::ButtonPressed(button) => {
                        if button == MouseButton::Left {
                            let position = {
                                let camera = self.scene_manager.get_active_camera();
                                let geo = self.renderer.get_geometry();

                                let phy_pos = *self.cursor_position.lock().unwrap();
                                let log_pos = phy_pos.to_logical(geo.scale_factor);

                                camera.get_position_from_cursor(log_pos)
                            };

                            let scene = self.scene_manager.get_active_scene();
                            scene.handle_click(position);
                        }
                    }
                    _ => {}
                }
            }
            Event::Keyboard(keyboard_event) => match keyboard_event {
                KeyboardEvent::KeyPressed { key, .. } => {
                    if let Some(dir) = Self::to_direction(&key) {
                        let camera = self.scene_manager.get_active_camera();
                        camera.notify_button_pressed(dir);
                    }
                }
                KeyboardEvent::KeyReleased { key, .. } => {
                    if let Some(dir) = Self::to_direction(&key) {
                        let camera = self.scene_manager.get_active_camera();
                        camera.notify_button_released(dir);
                    }
                }
                _ => {}
            },
            _ => {}
        }
    }

    fn to_direction(key: &Key) -> Option<InputDirection> {
        match key {
            Key::Character(c) => match c.as_str() {
                "w" => Some(InputDirection::Up),
                "a" => Some(InputDirection::Left),
                "s" => Some(InputDirection::Down),
                "d" => Some(InputDirection::Right),
                _ => None,
            },
            Key::Named(key::Named::ArrowUp) => Some(InputDirection::Up),
            Key::Named(key::Named::ArrowLeft) => Some(InputDirection::Left),
            Key::Named(key::Named::ArrowDown) => Some(InputDirection::Down),
            Key::Named(key::Named::ArrowRight) => Some(InputDirection::Right),
            _ => None,
        }
    }
}
