#![feature(let_chains)]
// See https://github.com/rust-lang/rust-clippy/issues/6353
#![allow(clippy::await_holding_refcell_ref)]
// Generated by uint crate
#![allow(clippy::assign_op_pattern)]
#![allow(clippy::ptr_offset_with_cast)]

mod clients;
mod config;
mod connection;
mod events;
mod failures;
mod ledger;
mod library;
mod link;
mod logic;
mod message;
mod metrics;
mod node;
mod object;
mod scene;
mod simulation;
mod stats;

#[cfg(feature = "runners")]
mod runners;

// The public API
pub use config::{
    Assert, Connectivity, Constraint, ExperimentConfiguration, NetworkConfiguration, ParameterType,
    ProtocolConfiguration, TestConfiguration,
};
pub use events::{BlockEvent, LinkEvent, NodeEvent, StatisticsEvent};
pub use failures::Failures;
pub use library::Library;
pub use link::{Bandwidth, Latency};
pub use logic::{Block, BlockId, GENESIS_BLOCK};
pub use message::Message;
pub use metrics::{ChainMetricType, ChainMetrics, MetricType, NetworkMetricType};
pub use node::{Location, NodeIndex};
pub use object::{Object, ObjectId};
pub use simulation::Simulation;
pub use stats::{GlobalStatistics, NodeStatistics};

#[cfg(feature = "runners")]
pub use runners::{EndlessRunner, ExperimentRunner, TestRunner};

type RcCell<T> = std::rc::Rc<std::cell::RefCell<T>>;
